random_fail:
  name: Random fail 👻
  description: A call to this service will randomly fail.

blueprint_import:
  name: Import blueprint 👻
  description: >-
    Import a blueprint.
  fields:
    url:
      name: URL
      description: The URL to import the blueprint from.
      required: true
      selector:
        text:

homeassistant_disable_config_entry:
  name: Disable a config entry 👻
  description: >-
    Disables a integration configuration entry.
  fields:
    config_entry_id:
      name: Config entry
      description: The integration configuration entry to disable.
      required: true
      selector:
        config_entry:

homeassistant_enable_config_entry:
  name: Enable a config entry 👻
  description: >-
    Enables a integration configuration entry.
  fields:
    config_entry_id:
      name: Config entry
      description: The integration configuration entry to enable.
      required: true
      selector:
        config_entry:

homeassistant_disable_device:
  name: Disable a device 👻
  description: >-
    Disables a device on the fly.
  fields:
    device_id:
      name: Device
      description: The device to disable.
      required: true
      selector:
        device:

homeassistant_enable_device:
  name: Enable a device 👻
  description: >-
    Enables a device on the fly.
  fields:
    device_id:
      name: Device
      description: The device to disable.
      required: true
      selector:
        device:

homeassistant_disable_entity:
  name: Disable an entity 👻
  description: >-
    Disables an entity (or entities) on the fly.
  fields:
    entity_id:
      name: Entity
      description: The entity/entities to disable.
      required: true
      selector:
        entity:
          multiple: true

homeassistant_enable_entity:
  name: Enable an entity 👻
  description: >-
    Enables an entity (or entities) on the fly.
  fields:
    entity_id:
      name: Entity
      description: The entity/entities to enable.
      required: true
      selector:
        entity:
          multiple: true


homeassistant_hide_entity:
  name: Hide an entity 👻
  description: >-
    Hides an entity (or entities) on the fly.
  fields:
    entity_id:
      name: Entity
      description: The entity/entities to hide.
      required: true
      selector:
        entity:
          multiple: true

homeassistant_unhide_entity:
  name: Unhide an entity 👻
  description: >-
    Unhides an entity (or entities) on the fly.
  fields:
    entity_id:
      name: Entity
      description: The entity/entities to unhide.
      required: true
      selector:
        entity:
          multiple: true

homeassistant_ignore_all_discovered:
  name: Ignore all currently discovered devices 👻
  description: >-
    Ignore all currently discovered devices that are shown on the integrations
    dashboard. This will not ignore devices that are discovered after this.
  fields:
    domain:
      name: Integration domain
      description: >-
        The integration domain to ignore all discovered devices for.
        If not provided, all domains will be considered to be ignored.
      required: false
      selector:
        text:

recorder_import_statistics:
  name: Import statistics 👻
  description: >-
    Import long-term statistics.
  fields:
    statistics_id:
      name: Statistics ID
      description: The statistics ID (entity ID) to import for.
      required: true
      selector:
        entity:
    name:
      name: Name
      description: The name of the statistics.
      required: false
      selector:
        text:
    source:
      name: Source
      description: The source of the statistics data.
      required: true
      selector:
        text:
    unit_of_measurement:
      name: Unit of measurement
      description: The unit of measurement of the statistics.
      required: false
      selector:
        text:
    has_mean:
      name: Has a mean
      description: If the statistics has a mean value.
      required: true
      selector:
        boolean:
    has_sum:
      name: Has a sum
      description: If the statistics has a sum value.
      required: true
      selector:
        boolean:
    stats:
      name: Statistics
      description: >-
        A list of mappings/dictionaries with statistics to import.
        The dictionaries must contain a "start" key with a datetime string
        other valid options are "mean", "sum", "min", "max", "last_reset", and
        "state". All of those are optional and either an integer or a float,
        except for "last_reset" which is a datetime string.
      required: true
      selector:
        object:
    
select_random:
  name: Select random option 👻
  description: >-
    Select an random option for a select entity.
  target:
    entity:
      domain: select
  fields:
    options:
      name: Options
      description: >-
        Limits the options to select from. If not provided, all options will be
        considered.
      required: false
      selector:
        object:

input_select_random:
  name: Select random option 👻
  description: >-
    Select an random option for a input_select entity.
  target:
    entity:
      domain: input_select
  fields:
    options:
      name: Options
      description: >-
        Limits the options to select from. If not provided, all options will be
        considered.
      required: false
      selector:
        object:

number_decrement:
  name: Decrease a number value 👻
  description: >-
    Decrease a number entity value by a certain amount.
  target:
    entity:
      domain: number
  fields:
    step:
      name: Amount
      description: >-
        The step to decrease the number with. If not provided, the step of the
        number entity will be used.
      required: false
      selector:
        number:

number_increment:
  name: Increase a number value 👻
  description: >-
    Increase a number entity value by a certain amount.
  target:
    entity:
      domain: number
  fields:
    step:
      name: Amount
      description: >-
        The step to increase the number with. If not provided, the step of the
        number entity will be used.
      required: false
      selector:
        number:

input_number_decrement:
  name: Decrease a input number value 👻
  description: >-
    Decrease an input number entity value by a certain amount.
  target:
    entity:
      domain: number
  fields:
    step:
      name: Amount
      description: >-
        The step to decrease the input number with. If not provided, the step
        of the number entity will be used.
      required: false
      selector:
        number:

input_number_increment:
  name: Increase a input number value 👻
  description: >-
    Increase a input number entity value by a certain amount.
  target:
    entity:
      domain: number
  fields:
    step:
      name: Amount
      description: >-
        The step to increase the input number with. If not provided, the step
        of the number entity will be used.
      required: false
      selector:
        number:
