random_fail:
  name: Random fail 👻
  description: A call to this service will randomly fail.

homeassistant_disable_config_entry:
  name: Disable a config entry 👻
  description: >-
    Disables a integration configuration entry.
  fields:
    config_entry_id:
      name: Config entry
      description: The integration configuration entry to disable.
      required: true
      selector:
        config_entry:

homeassistant_enable_config_entry:
  name: Enable a config entry 👻
  description: >-
    Enables a integration configuration entry.
  fields:
    config_entry_id:
      name: Config entry
      description: The integration configuration entry to enable.
      required: true
      selector:
        config_entry:

homeassistant_disable_device:
  name: Disable a device 👻
  description: >-
    Disables a device on the fly.
  fields:
    device_id:
      name: Device
      description: The device to disable.
      required: true
      selector:
        device:

homeassistant_enable_device:
  name: Enable a device 👻
  description: >-
    Enables a device on the fly.
  fields:
    device_id:
      name: Device
      description: The device to disable.
      required: true
      selector:
        device:

homeassistant_disable_entity:
  name: Disable an entity 👻
  description: >-
    Disables an entity (or entities) on the fly.
  fields:
    entity_id:
      name: Entity
      description: The entity/entities to disable.
      required: true
      selector:
        entity:
          multiple: true

homeassistant_enable_entity:
  name: Enable an entity 👻
  description: >-
    Enables an entity (or entities) on the fly.
  fields:
    entity_id:
      name: Entity
      description: The entity/entities to enable.
      required: true
      selector:
        entity:
          multiple: true


homeassistant_hide_entity:
  name: Hide an entity 👻
  description: >-
    Hides an entity (or entities) on the fly.
  fields:
    entity_id:
      name: Entity
      description: The entity/entities to hide.
      required: true
      selector:
        entity:
          multiple: true

homeassistant_unhide_entity:
  name: Unhide an entity 👻
  description: >-
    Unhides an entity (or entities) on the fly.
  fields:
    entity_id:
      name: Entity
      description: The entity/entities to unhide.
      required: true
      selector:
        entity:
          multiple: true
